server:
    port: 8989
spring:
    application:
        name: ems-user
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://115.159.103.185:4242/ems-parent?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
        username: lostfound
        password: lostfounddatabase
    redis:
        host: 115.159.103.185
        port: 6379
        password: getschwifty42
        database: 0
eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka
    #        registry-fetch-interval-seconds: 5  # client间隔多久去拉取服务注册信息,默认为30秒，通常用于网关服务
    instance:
        lease-expiration-duration-in-seconds: 10  # 表示server上一次收到client的心跳之后，等待下一次心跳的超时时间，在这个时间内若没收到下一次心跳，则将移除该instance，默认90s
        lease-renewal-interval-in-seconds: 5  # 客户端多久向server发送一次心跳，默认30s
mybatis:
    mapper-locations: classpath:mapper/*Mapper.xml
    type-aliases-package: cn.me.model.dto
